CREATE TABLE commentary_chapters (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    book_number INTEGER REFERENCES commentary_books(book_number) ON DELETE CASCADE NOT NULL,
    chapter_number TEXT UNIQUE NOT NULL,
    chapter_title TEXT NOT NULL
);