CREATE TABLE commentary_chapter_sections (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    section_number TEXT UNIQUE NOT NULL,
    chapter_number TEXT REFERENCES commentary_chapters(chapter_number) ON DELETE CASCADE NOT NULL,
    latin TEXT NOT NULL
);