CREATE TABLE commentary_chapter_intros (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    book INTEGER REFERENCES commentary_books(book_number) ON DELETE CASCADE NOT NULL,
    chapter TEXT REFERENCES commentary_chapters(chapter_number) ON DELETE CASCADE NOT NULL,
    intro_paragraph TEXT NOT NULL
);