CREATE TABLE commentary_comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    section TEXT REFERENCES commentary_chapter_sections(section_number) ON DELETE CASCADE NOT NULL,
    tag TEXT NOT NULL,
    comment TEXT NOT NULL,
    comment_order INTEGER NOT NULL
);