BEGIN;

TRUNCATE 
    commentary_comments
    RESTART IDENTITY CASCADE;

SET CLIENT_ENCODING to 'utf8';

INSERT INTO commentary_comments (section, tag, comment)
VALUES
    ('21-1-1', 'In parte operis...gessere', 'praefari introduces an indirect statement with me as the accsuative subject with scripturum (with esse supplied) as the main 
verb. Take praefari as the infinitive and me as an accusative subject.'),
('21-1-1', 'quod…scriptores', 'relative clause referring proleptically to the substance of the indirect statement (i.e. the claim that he is writing about the greatest war of all time).'),
('21-1-1', 'professi plerique sunt', 'a perfect, deponent indicative and the main verb of the relative clause.'),
('21-1-1', 'rerum scriptores', 'i.e. other writers of history'),
('21-1-1', 'gesta sint', 'subjunctive main verb in subordinate clause within indirect discourse (<a href="http://dcc.dickinson.edu/allen-greenough/Chapters/Chapter-577.html" target="_blank">A&G §577</a>)'),
('21-1-1', 'Hannibale duce', 'ablative absolute'),
('21-1-1', 'gessere', 'archaic/poetic form of gesserunt (3rd, plural, perfect, indicative active) from gero, gerere, gessi, gestus.'),
('21-1-1', 'quod', 'bellum is the antecedent.'),
('21-1-2', 'opibus', 'in this case, opibus refers to “military or political resources”  (L&S s.v. ops, 1B).'),
('21-1-2', 'his ipsis', 'datives of advantage (<a href="http://dcc.dickinson.edu/allen-greenough/Chapters/Chapter-577.html" target="_blank">A&G §234</a>) with ipsis functioning as an intensifying pronoun (“in and of itself”).'),
('21-1-2', 'propius periculum', 'typically an adjective, propius is here used in conjunction with the accusative as a preposition. The translation “closer to danger” 
is appropriate with the sense that the Romans (the eventual victors) were closer to destruction during this war than even the eventually-defeated Carthaginians (Walsh, 1985, pg. 121).'),
('21-1-2', 'uirium aut roboris', 'partitive genitive with tantum'),
('21-1-2', 'Mars', 'metonymy for “war” (L&S s.v. Mars II A).'),
('21-1-2', 'fuerint', 'perfect active subjunctive in a result clause (adeo in main clause, ut + subjunctive in subordinate clause)'),
('21-1-2', 'qui uicerunt', 'qui functions as the subject of the ut clause.'),
('21-1-3', 'quam', 'take with the comparative maioribus.'),
('21-1-3', 'inferrent...crederent', 'imperfect subjunctives in a quod clause of alleged reason(<a href="http://dcc.dickinson.edu/grammar/latin/causal-clauses" target="_blank">A&G 540</a>); introduces indirect statement.'),
('21-1-3', 'Poenis', 's.c. indignantibus'),
('21-1-3', 'imperitatum esse', 'impersonal here, although it is strongly implied that it was the Romans imposing this unjust rule.'),
('21-1-4', 'fama est', 'introduces indirect speech'),
('21-1-4', 'annorum ferme novem', 'novem is indeclinable, so it is here in the genitive modifying annorum. Both are genitives of quality (<a href="http://dcc.dickinson.edu/allen-greenough/Chapters/Chapter-345.html" target="_blank">A&G §345</a>).'),
('21-1-4', 'patri Hamilcari', 'blandientem (from blandior, iri, -, itus) takes the dative (patri Hamilcari) and introduces a purpose clause.'),
('21-1-4', 'cum...sacrificaret', 'cum temporal clause (<a href="http://dcc.dickinson.edu/allen-greenough/Chapters/Chapter-545.html" target="_blank">A&G §545</a>); subordinate clause in indirect statement usually take a subjunctive verb.'),
('21-1-4', 'traiecturus', 'future active participle modifying the subject of sacrifaceret, Hamilcar and expressing purpose (<a href="http://dcc.dickinson.edu/allen-greenough/Chapters/Chapter-499.html" target="_blank">A&G §499</a>).'),
('21-1-4', 'admotum…adactum', 's.c. esse; still in indirect discourse introduced by fama est with Hannibalem as the subject of both. Altaribus is in the dative as the compound admotum takes the dative. (<a href="http://dcc.dickinson.edu/allen-greenough/Chapters/Chapter-370.html" target="_blank">A&G §370</a>)'),
('21-1-4', 'iure iurando adactum', 'the verb adigere with iure iurando is an idiom for being compelled to swear an oath (L&S s.v. adigo II B).'),
('21-1-4', 'iure iurando...fore', 'starts an indirect statement with se as the accusative subject and fore (= futurum esse) as the infinitive, explaining the content 
of the oath sworn.'),
('21-1-5', 'ingentis spiritus', 'genitive of quality (<a href="http://dcc.dickinson.edu/allen-greenough/Chapters/Chapter-345.html" target="_blank">A&G §345</a>).'),
('21-1-5', 'Sicilia Sardiniaque amissae', 'subject of angebant'),
('21-1-5', 'nam', 'introduces an explanatory parenthetical clause which is an indirect statement expressing the thoughts of Hamilcar.'),
('21-2-1', 'se', 'object of gessit. This construction is Latin idiom for expressing how an individual or group conducts themselves (L&S s.v. gero II B).'),
('21-2-1', 'sub', 'with accusative can mean “after, just after, following” when referring to time (L&S s.v. sub II B).'),
('21-2-1', 'novem annis', 'the ablative normally indicates a particular point in time (sometimes called “time at which” or “time within which”), Livy occasionally uses the ablative as if an accusative of duration (Woodcock §54).'),
('21-2-2', 'augendo Punico imperio', 'gerund-replacing gerundive'),
('21-2-2', 'ut appareret…bellum', 'appareret is impersonal and initiates indirect statement completed by eum and agitare.'),
('21-2-2', 'quod gereret', 'eum (i.e. Hannibal) carries over as the subject of gereret'),
('21-2-2', 'maius', 'neuter acc. singular modifying bellum.'),
('21-2-2', 'si diutius vixissest', 'past contrary to fact conditional within indirect discourse, featuring a pluperfect subjunctive in the apodosis (if-clause) and future infinitive (i.e. the sentence’s main verb with Poenos as accusative subject) in the protasis (then-clause): “If he had lived longer…they would have” (<a href="http://dcc.dickinson.edu/allen-greenough/Chapters/Chapter-589.html" target="_blank">A&G §589</a>)'),
('21-2-2', 'qui', 'take Poenos as antecedent.'),
('21-2-2', 'Italiae', 'locative case.'),
('21-2-4', 'uti ferunt', 'Livy often employs fero to denote the relating of a story or report with a plural subject to refer to unspecified authors/Roman mythical traditions.'),
('21-2-4', 'adscitus', 'here indicates adoption (L&S s.v. ascisco II A)'),
('21-2-4', 'animi', 'subjective genitive with indolem'),
('21-2-5', 'hospitiis magis regulorum…gentibus', 'an example of Livian variatio - hospitiis goes with regulorum and conciliandis with nouis gentibus.'),
('21-2-6', 'nihilo', 'adverb related to nihil, meaning “in no way”.'),
('21-2-6', 'haud alio quam si evasisset voltu', 'haud modifies alio...voltu and the entire phrase governs the comparative quam,'),
('21-2-6', 'dolores', 'object of the ablative absolute superante laetitia.'),
('21-2-6', 'ut…praebuerit', 'result clause.'),
('21-2-6', 'ridentis', 'present active participle functioning as a substantive.'),
('21-2-7', 'mirae artis', 'genitive of characteristic with an implied vir.'),
('21-2-7', 'sollicitandis...iungendis', 'gerund-replacing gerundive'),
('21-3-1', 'haud dubia res fuit', 'introduces the indirect question that follows, with dubia res fuit standing a verb of the head.'),
('21-3-1', '<am successurus esset>', 'The brackets here indicate a lacuna (missing text in the manuscript). This reading is a conjecture by Walters (1929).'),        
('21-3-1', 'delatus...appellatus erat', 'main verbs of the relative clause.'),
('21-3-1', 'praerogatiuam militarem', 'proleptic object of sequebatur.'),
('21-3-2', 'actaque res', 'an idiomatic phrase used to describe debate, particularly in a judicial setting (L&S s.v.  ago II D 9).'),
('21-3-2', 'Barcinis nitentibus', 'ablative absolute introducing a purpose clause.'),
('21-3-2', 'adsuesceret', 'construe with the dative.'),
('21-3-3', 'tribuendum', 'passive periphrastic (s.c. esse) expressing obligation. See (link to periphrastics).'),
('21-3-4', 'florem aetatis', 'proleptic indirect accusative subject with censet is the verb of head.'),
('21-3-4', 'fruendum', 'a gerundive expressing purpose (<a href="http://dcc.dickinson.edu/allen-greenough/Chapters/Chapter-500.html" target="_blank">A&G §500.4</a>), agreeing with florem.'),
('21-3-5', 'videat…sint relicti …serviamus', 'subjunctive in fear clause; introduced by ne'),
('21-3-5', 'hereditarii', 'in apposition to exercitus'),
('21-3-5', 'cuius', 'the antecedent is eius'),
('21-3-5', 'parum', 'adverb.'),
('21-3-6', 'tenendum…docendum', 'gerundives with implied esse functioning as a passive periphrastic within indirect statement (insert link to periphrastics)'),       
('21-3-6', 'domi', 'locative case'),
('21-4-1', 'quisque', '“each”'),
('21-4-2', 'redditum', 's.c. esse'),
('21-4-2', 'credere', 'syncopated 3rd person plural perfect active form.'),
('21-4-2', 'intueri', 'main verb in the indirect statement introduced by credere with ueteres milites as the accusative subject,'),
('21-4-2', 'ad favorem conciliandum', 'gerund-replacing gerundive expressing purpose.'),
('21-4-3', 'parendum atque imparandum', 'gerunds in apposition to res, so they are also objects of the preposition ad expressing purpose'),
('21-4-3', 'discerneres', 'potential subjunctive that acts much like the apodosis of a present counterfactual condition that introduces an indirect question utrum…esset.'),
('21-4-4', 'malle…confidere…audere', 'historical infinitives (A&G ) used in imitation of Sallust, for more see Woodcock §21.'),
('21-4-4', 'quid', 'quid = aliquid'),
('21-4-4', 'agendum esset', 'frequentative use of the subjunctive (Walsh, ad loc.) as part of the passive periphrastic.'),
('21-4-5', 'plurimum…erat', 'erat is implied with both instances of plurimum.'),
('21-4-5', 'audaciae...consilii', 'genitives of quality.'),
('21-4-5', 'ad pericula capessenda', 'gerund-replacing gerundive expressing purpose.'),
('21-4-6', 'cibi potionisque', 'take with modus'),
('21-4-7', 'nullo…conspexerunt', 'notice the lack of coordinating conjunctions, a literary technique known as parataxis (<a href="http://dcc.dickinson.edu/allen-greenough/Chapters/Chapter-268.html" target="_blank">A&G §268</a>).'),
('21-4-7', 'id', 'refers to tempus'),
('21-4-7', 'quod...superesset', 'relative clause of characteristic (<a href="http://dcc.dickinson.edu/allen-greenough/Chapters/Chapter-535.html" target="_blank">A&G §535a</a>).'),
('21-4-10', 'meruit', 'refers here to serving a military campaign (L&S s.v. mereo, II.C).'),
('21-4-10', 'nulla re…praetermissa', 'ablative absolute'),
('21-4-10', 'quae…esset', 'relative clause of characteristic'),
('21-5-1', 'quo', 'Relatives are used more abundantly in Latin and in places where English may use a different construction. Here we might expect a demonstrative in English.'),
('21-5-2', 'prolatandum', 'gerundive replacing gerund.'),
('21-5-2', 'aliquis', 'Dropping ali after si, nisi, num, and ne is a convention as opposed to a hard and fast rule (Walsh 1985 129).'),
('21-5-3', 'in parte magis quam dicione carthaginiensium', 'magis quam compares parte to dicione and Carthanginiensium is a genitive of possession to both. In other words, the Olcandes are in the land of, but not under the control of the Carthaginians.'),
('21-5-3', 'quibus oppugnandis', 'quibus is a connecting relative (<a href="http://dcc.dickinson.edu/grammar/latin/relative-pronouns" target="_blank">A&G 303 2</a>).'),
('21-5-3', 'rerum serie...posset', 'posset introduces uiderei as a complementary infinitive. Take with petisse and tractus.'),
('21-5-4', 'quo', 'connecting relative (<a href="http://dcc.dickinson.edu/grammar/latin/relative-pronouns" target="_blank">A&G 303 2</a>)'),
('21-5-5', 'ibi…bellum', 'the main kernel is promutum bellum. The gerundive pratiendo and the gerund replacing gerundive exolvendo are ablatives of means.'),
('21-5-5', 'stipendioque praeterito', '“arrears of pay” (Walsh 1989)'),
('21-5-7', 'ab Hermandica…iunxisset', 'the cum clause extends all the way back to ab Hermandica and takes profugi as its subject.'),
('21-5-7', 'priore aestate domitae gentis', 'in apposistion to Olcadum.'),
('21-5-9', 'cum prima', '“as soon as”.'),
('21-5-9', 'invadere', 'take with statuit'),
('21-5-11', 'invicta acies si aequo dimicaretur campo', 'The imperfect subjunctive is used in past unreal conditions is common on Livy and earlier Latin authors (Woodcock 199).'),
('21-5-13', 'alveo', '“river bed” (L&S s.v. alveus II F).'),
('21-5-14', 'Quippe ubi…fidens', 'i.e. quippe in quo, “since on the riverbed” (Walsh 1985 131).  c.f. <a href="http://dcc.dickinson.edu/allen-greenough/Chapters/Chapter-535.html" target="_blank">A&G §535</a>. E. for more on the equivalent clause and its expression of causation.'),
('21-5-14', 'uel...uel', 'contrasting the footsoldier and the cavalryman.'),
('21-5-14', 'eques corpore amrisque liber', 'corpore armisque are ablatives of separation dependent on liber posset'),
('21-5-14', 'gereret', 'potential subjunctive'),
('21-5-16', 'quibus', 'take as a dative of reference with regressus.'),
('21-5-16', 'reciperent', 'c.f. <a href="http://dcc.dickinson.edu/allen-greenough/Chapters/Chapter-550.html" target="_blank">A&G §550</a>');

COMMIT;